### ISSUE TITLE
Hi Please help on C socket

### ISSUE THREAD

**Issue by carter3rix** [ajvuik/Nixie_Clock#1]
Hello I read your comment on using C socket with ArduinoJson to process some data from openweather
I trying to similar implementation but seems lost.. 
Opening a http connection and receiving to process in C
Please can help me out...
Thank you...

**Comment by ajvuik** [comment]
Please look at the next peace of code:
```

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>

#include <netinet/tcp.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <netdb.h>

#include "ArduinoJson/ArduinoJson.h"

#define BUFFER_SIZE 2048

//Init Json buffer
StaticJsonBuffer<BUFFER_SIZE> jsonBuffer;

//Init API
char server[] = "api.openweathermap.org";
char get[] = "GET /data/2.5/weather?id=2755420&mode=json&units=metric&lang=nl&APPID=YOUR APPID HERE HTTP/1.1\r\nHost: api.openweathermap.org\r\n\r\n";
int port = 80;

//prototypes
int socket_connect(char *host, in_port_t port);

int main(int argc, char *argv[]){
	int fd;
	char buffer[BUFFER_SIZE];
	
	//printf("Open the connection\n");       
	fd = socket_connect(server, port);
	//printf("Send the GET to the API\n"); 
	write(fd, get, strlen(get)); // write(fd, char[]*, len);  
	bzero(buffer, BUFFER_SIZE);
	//printf("read the buffer\n");
	read(fd, buffer, BUFFER_SIZE - 1);
	
	char t_buffer[BUFFER_SIZE];
	bzero(t_buffer, BUFFER_SIZE);
	char* ch_P = strstr(buffer, "\r\n\r\n");
	ch_P=ch_P+4;
	int i = 0;
	while(*ch_P != '\0' ){
		t_buffer[i]=*ch_P;
		i++;
		ch_P++;
	}
		
	JsonObject& weatherJson = jsonBuffer.parseObject(t_buffer);

	if(!weatherJson.success()){
		printf("Parsing failed!");
		return -1;
	}
	printf("Het weer in: %s\n", (const char *)weatherJson["name"]);
    JsonArray& weather = weatherJson["weather"];
    JsonObject& weather0 = weather[0];
    printf("%s\n", (const char *)weather0["description"]);
    printf("Huidige temperatuur: ");
    printf("%s", (const char *)weatherJson["main"]["temp"]);
    printf("°C\n");
	shutdown(fd, SHUT_RDWR); 
	//printf("Close the file handler\n");
	close(fd); 
	//printf("Bye\n");
	return 0;
}


int socket_connect(char *host, in_port_t port){
	struct hostent *hp;
	struct sockaddr_in addr;
	int on = 1, sock;     

	if((hp = gethostbyname(host)) == NULL){
		herror("gethostbyname");
		exit(1);
	}
	bcopy(hp->h_addr, &addr.sin_addr, hp->h_length);
	addr.sin_port = htons(port);
	addr.sin_family = AF_INET;
	sock = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
	setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (const char *)&on, sizeof(int));

	if(sock == -1){
		perror("setsockopt");
		exit(1);
	}
	
	if(connect(sock, (struct sockaddr *)&addr, sizeof(struct sockaddr_in)) == -1){
		perror("connect");
		exit(1);

	}
	return sock;
}


```

I hope this helps

**Comment by carter3rix** [comment]
Thanks works great...
I have separated the into to 2 files .... One which the .h which holds the implementation and the other the file itself.. 
sample_socket .h
`#ifndef SAMP_SOCKET
#define SAMP_SOCKET
 
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>

#include <netinet/tcp.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <netdb.h>

#include "ArduinoJson/ArduinoJson.h"

#define BUFFER_SIZE 2048

//Init Json buffer
StaticJsonBuffer<BUFFER_SIZE> jsonBuffer;

//prototypes
int socket_connect(char *host, in_port_t port);

int socket_connect(char *host, in_port_t port){
	struct hostent *hp;
	struct sockaddr_in addr;
	int on = 1, sock;     

	if((hp = gethostbyname(host)) == NULL){
		herror("gethostbyname");
		exit(1);
	}
	bcopy(hp->h_addr, &addr.sin_addr, hp->h_length);
	addr.sin_port = htons(port);
	addr.sin_family = AF_INET;
	sock = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
	setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (const char *)&on, sizeof(int));

	if(sock == -1){
		perror("setsockopt");
		exit(1);
	}
	
	if(connect(sock, (struct sockaddr *)&addr, sizeof(struct sockaddr_in)) == -1){
		perror("connect");
		exit(1);

	}
	return sock;
}

#endif `
the other file holds the implementation sample
sample_socket .cpp
`#include "samp_socket.h"

//Init API
char server[] = "api.openweathermap.org";
char get[] = "GET /data/2.5/weather?id=2172797&mode=json&units=metric&lang=en&APPID=aa47a6236a69dd8649b225b6a08f0385 HTTP/1.1\r\nHost: api.openweathermap.org\r\n\r\n";
int port = 80;

int main(int argc, char *argv[]){
	int fd;
	char buffer[BUFFER_SIZE];
	
	//printf("Open the connection\n");
	fd = socket_connect(server, port);
	//printf("Send the GET to the API\n");
	write(fd, get, strlen(get)); // write(fd, char[]*, len);
	bzero(buffer, BUFFER_SIZE);
	//printf("read the buffer\n");
	read(fd, buffer, BUFFER_SIZE - 1);
	
	char t_buffer[BUFFER_SIZE];
	bzero(t_buffer, BUFFER_SIZE);
	char* ch_P = strstr(buffer, "\r\n\r\n");
	ch_P=ch_P+4;
	int i = 0;
	while(*ch_P != '\0' ){
		t_buffer[i]=*ch_P;
		i++;
		ch_P++;
	}

	JsonObject& weatherJson = jsonBuffer.parseObject(t_buffer);

	if(!weatherJson.success()){
		printf("Parsing failed!");
		return -1;
	}
	printf("Het weer in: %s\n", (const char *)weatherJson["name"]);
    JsonArray& weather = weatherJson["weather"];
    JsonObject& weather0 = weather[0];
    printf("%s\n", (const char *)weather0["description"]);
    printf("Huidige temperatuur: ");
    printf("%s", (const char *)weatherJson["main"]["temp"]);
    printf("°C\n");
	shutdown(fd, SHUT_RDWR); 
	//printf("Close the file handler\n");
	close(fd); 
	//printf("Bye\n");
	return 0;
}
`
Now i want to do something like 
GET and POST
I want to hold some value to memset
that is memset(input1, char*, sizeof(input1))
memset(input2, char*, sizeof(input2))
where i construct inputs into json structure of bytesArray of input1 and input2 and do a post to a socket
then listen to socket to get whater response it return... Thanks any help...
